name: Bleeding Edge Build
on:
  workflow_dispatch:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.6
    - name: Setup msbuild
      uses: microsoft/setup-msbuild@v2
    - name: Build Project
      run: msbuild "Interweb Searcher.sln" /t:Build /p:Configuration=Debug
    - name: Resolve Short Commit Hash
      if: startsWith(github.ref, 'refs/tags/') == false
      id: get_hash
      shell: bash
      run: echo "hash=`git rev-parse --short HEAD`" >> $GITHUB_OUTPUT
    - name: Upload Debug Build x86
      if: startsWith(github.ref, 'refs/tags/') == false
      uses: actions/upload-artifact@v4.3.3
      with:
        name: Interweb.Searcher.x86-${{ steps.get_hash.outputs.hash }}
        path: ./bin/x86/Debug/
    - name: Upload Debug Build x64
      if: startsWith(github.ref, 'refs/tags/') == false
      uses: actions/upload-artifact@v4.3.3
      with:
        name: Interweb.Searcher.x64-${{ steps.get_hash.outputs.hash }}
        path: ./bin/x64/Debug/